### ISSUE TITLE
(centos) Converted image have no text . 

### ISSUE THREAD

**Issue by gabrieltong** [robflynn/pdftoimage#1]
Hey there 

   I have a pdf , which is ok on mac , but on centos(6.6 final) , the images are only the background ? do you want to see the sample ?

**Comment by robflynn** [comment]
Interesting. Sure, if you'd like to email it - rob@thingerly.com. I have, on occasion, run across a few PDFs that like to misbehave.

**Comment by robflynn** [comment]
Can't remember if this got properly resolved or not and don't have a way to test with the original file. Going to go ahead and close this.
